apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ip-lookup-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: ip-lookup
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
